### ISSUE TITLE
[Ranges] package cannot be found

### ISSUE THREAD

**Issue by andywu188** [Latency/NDesk.Options#2]
**Describe the bug**
In Nuget, the Ranges dependency package cannot be found

https://www.nuget.org/packages/Ranges/

**Comment by Latency** [comment]
Hello Andy,

For ranges & indicies:
This would only be a required dependancy for .NET ~4.5.2 targets as an external port.

I may have overlooked adding the target rule specific for this framework ver within the MSBuild rules.

Compiler c# 8.0+, this library is built in.

I will repack it in the meantime, there may be a project on my repo list for this.

-Latency

References:
[Ranges](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges)
